Remove leetcode action health check

diff --git a/.github/workflows/leetcode-update.yml b/.github/workflows/leetcode-update.yml
--- a/.github/workflows/leetcode-update.yml
+++ b/.github/workflows/leetcode-update.yml
@@ -80,27 +80,27 @@ jobs:
             --health-interval=5s --health-timeout=3s --health-retries=24 \
             ghcr.io/${{ steps.lc.outputs.value }}/peerprep-question-backend:latest
 
-      - name: Wait for Question to be healthy (or fail fast)
-        run: |
-          set -euo pipefail
-          for i in {1..60}; do
-            state=$(docker inspect question-backend --format '{{.State.Status}}')
-            health=$(docker inspect question-backend --format '{{if .State.Health}}{{.State.Health.Status}}{{end}}')
-            echo "question-backend State=$state Health=$health"
+      # - name: Wait for Question to be healthy (or fail fast)
+      #   run: |
+      #     set -euo pipefail
+      #     for i in {1..60}; do
+      #       state=$(docker inspect question-backend --format '{{.State.Status}}')
+      #       health=$(docker inspect question-backend --format '{{if .State.Health}}{{.State.Health.Status}}{{end}}')
+      #       echo "question-backend State=$state Health=$health"
 
-            # Show last healthcheck output when it's not healthy yet
-            docker inspect question-backend \
-              --format='{{range .State.Health.Log}}{{printf "%s - %s\n" .End .Output}}{{end}}' | tail -n 3 || true
+      #       # Show last healthcheck output when it's not healthy yet
+      #       docker inspect question-backend \
+      #         --format='{{range .State.Health.Log}}{{printf "%s - %s\n" .End .Output}}{{end}}' | tail -n 3 || true
 
-            if [ "$state" = "exited" ] || [ "$state" = "dead" ]; then
-              echo "::error::question-backend exited early"
-              docker logs question-backend || true
-              exit 1
-            fi
-            [ "$health" = "healthy" ] && break
-            sleep 2
-          done
-          [ "$(docker inspect question-backend --format '{{.State.Health.Status}}')" = "healthy" ]
+      #       if [ "$state" = "exited" ] || [ "$state" = "dead" ]; then
+      #         echo "::error::question-backend exited early"
+      #         docker logs question-backend || true
+      #         exit 1
+      #       fi
+      #       [ "$health" = "healthy" ] && break
+      #       sleep 2
+      #     done
+      #     [ "$(docker inspect question-backend --format '{{.State.Health.Status}}')" = "healthy" ]
 
       - name: Trigger seed-batch
         run: |
