Refactor from matrix to individual jobs

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -9,22 +9,8 @@ on:
       - "**"
 
 jobs:
-  lint:
+  matching-ui-lint:
     runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        microservice:
-          # Add one entry per microservice
-          - name: matching-ui
-            path: ./ui-services/matching-ui-service
-          - name: questions-ui
-            path: ./ui-services/question-ui-service
-          - name: collab-ui
-            path: ./ui-services/collab-ui-service
-          - name: user-ui
-            path: ./ui-services/user-ui-service
-          - name: history-ui
-            path: ./ui-services/history-ui-service
     steps:
       - name: Set REVIEWDOG_GITHUB_API_TOKEN
         run: echo "REVIEWDOG_GITHUB_API_TOKEN=${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}" >> $GITHUB_ENV
@@ -40,40 +26,155 @@ jobs:
 
       - name: Install dependencies
         run: |
-          cd ${{ matrix.microservice.path }}
+          cd ./ui-services/matching-ui-service
           npm install --frozen-lockfile
-
-      - name: Set up Reviewdog
-        uses: reviewdog/action-setup@d8edfce3dd5e1ec6978745e801f9c50b5ef80252
-        with:
-          reviewdog_version: latest
 
       - name: Run ESLint and Reviewdog
         run: |
-          cd ${{ matrix.microservice.path }}
-
-          npx eslint . || true
-          eslint_exit_code=$? 
+          cd ./ui-services/matching-ui-service
+          npx eslint . || exit_code=$?
+          eslint_exit_code=$exit_code
 
           if [ $eslint_exit_code -ne 0 ]; then
-            echo "lint-failed=true" >> $GITHUB_ENV
-            echo "ESLint failed"  # Optional: For debugging purposes
-          else
-            echo "lint-failed=true" >> $GITHUB_ENV
+            echo "ESLint failed for matching-ui"
+            exit 1
           fi
 
           npx eslint --format json . > eslint-report.json
           cat eslint-report.json | reviewdog -f=eslint -name="eslint" -reporter=github-pr-review -level=error
-        continue-on-error: true
 
-      - name: Print Environment Variables
-        run: |
-          echo "Printing environment variables..."
-          echo "lint-failed=${{ env.lint-failed }}"
+  questions-ui-lint:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Set REVIEWDOG_GITHUB_API_TOKEN
+        run: echo "REVIEWDOG_GITHUB_API_TOKEN=${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}" >> $GITHUB_ENV
 
-      - name: Review Lint Check Status
-        if: ${{ env.lint-failed == 'true' }}
+      - name: Checkout Repository
+        uses: actions/checkout@v3
+
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: "20.x"
+          cache: "npm"
+
+      - name: Install dependencies
         run: |
-          echo "One or more microservices have failed linting."
-          exit 1
-        continue-on-error: true
+          cd ./ui-services/question-ui-service
+          npm install --frozen-lockfile
+
+      - name: Run ESLint and Reviewdog
+        run: |
+          cd ./ui-services/question-ui-service
+          npx eslint . || exit_code=$?
+          eslint_exit_code=$exit_code
+
+          if [ $eslint_exit_code -ne 0 ]; then
+            echo "ESLint failed for questions-ui"
+            exit 1
+          fi
+
+          npx eslint --format json . > eslint-report.json
+          cat eslint-report.json | reviewdog -f=eslint -name="eslint" -reporter=github-pr-review -level=error
+
+  collab-ui-lint:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Set REVIEWDOG_GITHUB_API_TOKEN
+        run: echo "REVIEWDOG_GITHUB_API_TOKEN=${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}" >> $GITHUB_ENV
+
+      - name: Checkout Repository
+        uses: actions/checkout@v3
+
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: "20.x"
+          cache: "npm"
+
+      - name: Install dependencies
+        run: |
+          cd ./ui-services/collab-ui-service
+          npm install --frozen-lockfile
+
+      - name: Run ESLint and Reviewdog
+        run: |
+          cd ./ui-services/collab-ui-service
+          npx eslint . || exit_code=$?
+          eslint_exit_code=$exit_code
+
+          if [ $eslint_exit_code -ne 0 ]; then
+            echo "ESLint failed for collab-ui"
+            exit 1
+          fi
+
+          npx eslint --format json . > eslint-report.json
+          cat eslint-report.json | reviewdog -f=eslint -name="eslint" -reporter=github-pr-review -level=error
+
+  user-ui-lint:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Set REVIEWDOG_GITHUB_API_TOKEN
+        run: echo "REVIEWDOG_GITHUB_API_TOKEN=${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}" >> $GITHUB_ENV
+
+      - name: Checkout Repository
+        uses: actions/checkout@v3
+
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: "20.x"
+          cache: "npm"
+
+      - name: Install dependencies
+        run: |
+          cd ./ui-services/user-ui-service
+          npm install --frozen-lockfile
+
+      - name: Run ESLint and Reviewdog
+        run: |
+          cd ./ui-services/user-ui-service
+          npx eslint . || exit_code=$?
+          eslint_exit_code=$exit_code
+
+          if [ $eslint_exit_code -ne 0 ]; then
+            echo "ESLint failed for questions-ui"
+            exit 1
+          fi
+
+          npx eslint --format json . > eslint-report.json
+          cat eslint-report.json | reviewdog -f=eslint -name="eslint" -reporter=github-pr-review -level=error
+
+  history-ui-lint:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Set REVIEWDOG_GITHUB_API_TOKEN
+        run: echo "REVIEWDOG_GITHUB_API_TOKEN=${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}" >> $GITHUB_ENV
+
+      - name: Checkout Repository
+        uses: actions/checkout@v3
+
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: "20.x"
+          cache: "npm"
+
+      - name: Install dependencies
+        run: |
+          cd ./ui-services/history-ui-service
+          npm install --frozen-lockfile
+
+      - name: Run ESLint and Reviewdog
+        run: |
+          cd ./ui-services/history-ui-service
+          npx eslint . || exit_code=$?
+          eslint_exit_code=$exit_code
+
+          if [ $eslint_exit_code -ne 0 ]; then
+            echo "ESLint failed for collab-ui"
+            exit 1
+          fi
+
+          npx eslint --format json . > eslint-report.json
+          cat eslint-report.json | reviewdog -f=eslint -name="eslint" -reporter=github-pr-review -level=error
