Add manual failure when check fails

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -45,3 +45,9 @@ jobs:
           cd ${{ matrix.microservice.path }}
           npm run lint
         continue-on-error: true
+
+      - name: Review Lint Check Status
+        if: ${{ failure() }}
+        run: |
+          echo "One or more microservices have failed linting."
+          exit 1
